package templates

import "github.com/rdeusser/vulcan/internal/scaffold"

var _ scaffold.Template = &Readme{}

type Readme struct {
	scaffold.TemplateMixin
	scaffold.ProjectNameMixin
}

func (t *Readme) GetIfExistsAction() scaffold.IfExistsAction {
	return t.IfExistsAction
}

func (t *Readme) SetTemplateDefaults() error {
	if t.Path == "" {
		t.Path = "README.md"
	}

	t.TemplateBody = readmeTemplate
	t.IfExistsAction = scaffold.Skip

	return nil
}

const readmeTemplate = `# {{ .ProjectName }}

Generated by the vulcan project generator.

## Requirements

## Usage`
